/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        canvas: 'var(--dash-canvas)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
          soft: 'var(--color-surface-soft)',
          pill: 'var(--dash-surface-pill)',
          capsule: 'var(--dash-surface-capsule)',
          hover: 'var(--color-surface-hover)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          subtle: 'var(--color-border-subtle)',
          focus: 'var(--color-border-focus)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          subtle: 'var(--color-text-subtle)',
        },
        brand: {
          DEFAULT: 'var(--dash-brand)',
          hover: 'var(--dash-brand-hover)',
        },
        signal: 'var(--color-signal)',
        data: 'var(--color-data)',
        critical: 'var(--color-critical)',
        confirmed: 'var(--color-confirmed)',
        success: 'var(--dash-success)',
        warning: 'var(--dash-warning)',
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
        serif: ['"IBM Plex Serif"', 'ui-serif', 'Georgia', 'serif'],
      },
      borderRadius: {
        sm: '10px',
        control: '12px',
        input: '12px',
        icon: '14px',
        card: '24px',
        modal: '26px',
        pill: '9999px',
      },
      boxShadow: {
        subtle: 'var(--shadow-subtle)',
        elevated: 'var(--shadow-elevated)',
        dashboard: 'var(--dash-shadow-card)',
        'dashboard-hover': 'var(--dash-shadow-hover)',
        modal: 'var(--shadow-modal)',
        pill: 'var(--dash-shadow-pill)',
        tooltip: 'var(--dash-shadow-tooltip)',
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      transitionDuration: {
        DEFAULT: '180ms',
        fast: '150ms',
      },
      fontSize: {
        'page-title': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em' }],
        'section-title': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em' }],
        'card-title': ['16px', { lineHeight: '22px', letterSpacing: '-0.01em' }],
        'body': ['14px', { lineHeight: '20px' }],
        'data': ['13px', { lineHeight: '18px' }],
        'secondary': ['13px', { lineHeight: '18px' }],
        'small': ['12px', { lineHeight: '16px' }],
        'metric': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em' }],
      },
      zIndex: {
        header: '40',
        sidebar: '50',
        dropdown: '100',
        'modal-backdrop': '9990',
        modal: '9999',
        popover: '10001',
        tooltip: '10002',
      },
    },
  },
  plugins: [],
}
